---
language: python
services: docker

env:
  global:
    - ROLE_NAME: docker
  matrix:
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: debian9

install:
  - pip install molecule yamllint ansible-lint docker

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME willenglishiv.$ROLE_NAME
  - cd willenglishiv.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
